### ISSUE TITLE
Why didn't you use 'contrib' in the name?

### ISSUE THREAD

**Issue by juggledad** [automatikas/Node-red-Nest-thermostat#3]
I just happened to stumble on this node and wondered why you didn't use the 'node-red-contrib-xxxx' naming conventions? It doesn't show up in the node-red flows (https://flows.nodered.org) where it would get lots more exposure.

Just wondering.

**Comment by automatikas** [comment]
Name convention maters for nodes not for flows. Why it was not on the node-red page is just to avoid several place where i have to edit the code if needed. They use gist instead repositories and that's kind of limit the functions what you have on normal git repository. 
Ok let's do it the hard-way :) 

Thanks for the input @juggledad!

https://flows.nodered.org/flow/f75a4828e586723d18a89a5c1d22681f

**Comment by automatikas** [comment]
I see it is not recommended to rename gist  :)

https://flows.nodered.org/flow/6e4649bc6d6529078cbb731610242eac
