### ISSUE TITLE
widget resetting on page refresh

### ISSUE THREAD

**Issue by qwertangel** [automatikas/Node-red-Nest-thermostat#5]
I am using the fahrenheit example. I noticed that once I set the values it shows nicely in dashboard. However as soon as I refresh the dashboard page, everything resets. i.e. widget goes back to 'off' and 50 min etc. What am I doing wrong ?

**Comment by qwertangel** [comment]
never mind. I found that node had a setting to restore value on restore.

**Comment by brunoamaral** [comment]
For others having the same issue, you need to tick the last checkbox:
![image](https://user-images.githubusercontent.com/543344/105089315-dfb87700-5a94-11eb-8cb8-a6e2c19b31d5.png)
