### ISSUE TITLE
Not an issue, but nice to have

### ISSUE THREAD

**Issue by nonix** [automatikas/Node-red-Nest-thermostat#6]
Hi, thank you for porting this work to NR.

Would it be possible to swap the ambient temp with target temp? 

The idea is to see at first glance the current (ambient) temp in the middle of NEST while the  set point is just a number on dial (currently the ambient).

My HTML/JS skills are not at best ;-)

Thank you,
 N.

**Comment by elperepat** [comment]
I want the same. I'll give it a try.

**Comment by elperepat** [comment]
See my [pull request](https://github.com/automatikas/Node-red-Nest-thermostat/pull/8). I implemented it.

**Comment by elperepat** [comment]
To improve code visibility on github and to ease with diff, you should maybe use a separate file to put the code of the template node.

The diff tool from github would be able to spot the differences. I updated my pull request accordingly.
